### ISSUE TITLE
Garbled sound from 32khz tracks

### ISSUE THREAD

**Issue by fanfani** [andrew-taylor/read_dat#1]
hello, we are recovering sounds from a big DAT archive (about a hundred live sets recorded in various places in Rome - Italy - in the mid-90s) using firmware-hacked drives and read_dat.

while 48khz tracks are perfectly converted in wav by read_dat, all 32khz tracks always result in garbled sounds when converted to wav.

in the directory http://darkpand.net/fedingo/fedingo63/

there's a sample tape dump you can fetch and convert to reproduce the problem:

http://darkpand.net/fedingo/fedingo63/raw_tape_image.489

conversion should result in "good" 48khz tracks such as 

http://darkpand.net/fedingo/fedingo63/fedingo63_1995-01-01-01-22-14.wav

and "bad" 32khz tracks such as

http://darkpand.net/fedingo/fedingo63/fedingo63_1995-01-01-00-05-30.wav

are we missing something? is it a read_dat bug? 

thank you! :-)

**Comment by andrew-taylor** [comment]
f4ea97b fixes a bug which appears to be the problem.

**Comment by fanfani** [comment]
wow! it works :-)
